version: "3.8"

services:
  postgress:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nest-clean
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
